updates:
  - directory: /
    open-pull-requests-limit: 1
    package-ecosystem: gradle
    schedule:
      interval: weekly
  - directory: /java-client/
    open-pull-requests-limit: 1
    package-ecosystem: gradle
    schedule:
      interval: weekly
version: 2
