name: Unit

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ 11 ]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: adopt

      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Run Unit Test
        run: ./gradlew clean unitTest
