name: Integration with Released OpenSearch

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
env:
  MAJOR_VERSION_UNRELEASED: 'false' # this environment variable should be set to true when a new major version is released.

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        opensearch_version:
          - 2.0.0
        java:
          - 11
          - 14
    if env.MAJOR_VERSION_UNRELEASED == 'true'
    steps:
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Run Docker
        run: |
          docker-compose --project-directory .ci/opensearch build --build-arg OPENSEARCH_VERSION=${{ matrix.opensearch_version }}
          docker-compose --project-directory .ci/opensearch up -d
          sleep 60

      - name: Run Integration Test
        run: ./gradlew clean integrationTest

      - name: Stop Docker
        run: |
          docker-compose --project-directory .ci/opensearch down
